name: test

on: 
  push:
    branches:
      - main
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    tag: "Manual Run"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run checks
      run: |
        # Install
        uv pip install .[dev]

        # Lint and test
        uv run --locked pyright .
        uv run --locked ruff check .
        uv run --locked pytest .

        # Build docs to make sure they work
        uv run --locked mkdocs build
